Console.WriteLine("Hamburguesa Clasica:");
Hamburguesa hamburguesaClasica = new Hamburguesa("Blanco", "Carne de Res", 10);
hamburguesaClasica.MostrarPrecio();
hamburguesaClasica.AgregarIngrediente("Lechuga", 1);
hamburguesaClasica.AgregarIngrediente("Tomate", 1);
hamburguesaClasica.MostrarPrecioFinal();
Console.WriteLine();
HamburguesaSaludable hamburguesaSaludable = new HamburguesaSaludable("Integral", "Pavo", 12);
hamburguesaSaludable.MostrarPrecio();
hamburguesaSaludable.AgregarIngrediente("Pimiento", 1);
hamburguesaSaludable.AgregarIngrediente("Cebolla", 1);
hamburguesaSaludable.MostrarPrecioFinal();
Console.WriteLine();
HamburguesaPremium hamburguesaPremium = new HamburguesaPremium("Blanco", "Pollo", 15);
hamburguesaPremium.MostrarPrecio();
hamburguesaPremium.AgregarExtra("Papitas", 2);
hamburguesaPremium.AgregarExtra("Bebida", 2);
hamburguesaPremium.MostrarPrecioFinal();